version: "1"
services:
  db:
    build: .
    image: cinema_base_dump
    container_name: cinema_base_dump
    environment:
      POSTGRES_DB: cinema_collection_service_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./clone.sh:/docker-entrypoint-initdb.d/clone.sh
    ports:
      - "5432:5432"
