eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

server:
  port: 8802

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cinema_collection_service_db
#    jdbc:postgresql://${SERVER:localhost}:${PORT:5432}/${DB_NAME:cinema_collection_service_db}
    #        jdbc:postgresql://         localhost :       5432/           cinema_content_service_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:create}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: false
